-- PROPERTY DROP DOWNS
INSERT INTO t_pdp VALUES (1,  'connector_color', 'White');
INSERT INTO t_pdp VALUES (2,  'connector_color', 'Silver');
INSERT INTO t_pdp VALUES (3,  'connector_color', 'Gray');
INSERT INTO t_pdp VALUES (4,  'connector_color', 'Black');
INSERT INTO t_pdp VALUES (5,  'connector_color', 'Maroon');
INSERT INTO t_pdp VALUES (6,  'connector_color', 'Yellow');
INSERT INTO t_pdp VALUES (7,  'connector_color', 'Olive');
INSERT INTO t_pdp VALUES (8,  'connector_color', 'Lime');
INSERT INTO t_pdp VALUES (9,  'connector_color', 'Green');
INSERT INTO t_pdp VALUES (10, 'connector_color', 'Aqua');
INSERT INTO t_pdp VALUES (11, 'connector_color', 'Teal');
INSERT INTO t_pdp VALUES (12, 'connector_color', 'Blue');
INSERT INTO t_pdp VALUES (13, 'connector_color', 'Navy');
INSERT INTO t_pdp VALUES (14, 'connector_color', 'Fuchsia');
INSERT INTO t_pdp VALUES (15, 'connector_color', 'Purple');
INSERT INTO t_pdp VALUES (16, 'connector_color', 'Red');
INSERT INTO t_pdp VALUES (17, 'connector_type', 'Airbag');
INSERT INTO t_pdp VALUES (18, 'connector_type', 'Clip');
INSERT INTO t_pdp VALUES (19, 'connector_type', 'Grommet');
INSERT INTO t_pdp VALUES (20, 'connector_type', 'Simple Connector');
INSERT INTO t_pdp VALUES (21, 'connector_type', 'Cosse');
INSERT INTO t_pdp VALUES (22, 'connector_type', 'FuseBox');
INSERT INTO t_pdp VALUES (23, 'connector_type', 'FuseBox Torque');
INSERT INTO t_pdp VALUES (24, 'connector_type', 'Antenne');